# Generated by Django 4.2.16 on 2025-07-14 23:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='media/%Y/%m/')),
                ('poster', models.ImageField(blank=True, upload_to='media/posters/%Y/%m/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('object_id', models.UUIDField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('app_label', models.CharField(blank=True, help_text='Logical grouping of where this media is used: blog, events, website, etc.', max_length=50)),
                ('context', models.CharField(blank=True, help_text="Optional context e.g. 'homepage-banner', 'event-photos', 'post-gallery'", max_length=100)),
                ('media_type', models.CharField(choices=[('primary', 'Primary'), ('gallery', 'Gallery'), ('embedded', 'Embedded')], default='gallery', help_text='Role of this media in the context', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
