# Generated by Django 4.1 on 2023-12-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0005_rename_child_contestant_alter_payment_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.contestant')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.judgingcriteria')),
            ],
        ),
        migrations.AddField(
            model_name='judgingcriteria',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.maincategory'),
        ),
    ]
