# Generated by Django 4.1 on 2023-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgingcriteria',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
