# Generated by Django 4.2.16 on 2025-07-15 00:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_alter_user_role_authorprofile'),
        ('register', '0007_approval_amount'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judgingcriteria',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['name'], 'verbose_name': 'Main Category', 'verbose_name_plural': 'Main Categories'},
        ),
        migrations.RemoveField(
            model_name='judgecomment',
            name='contestant',
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='participant',
            field=models.ForeignKey(default=607, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='register.participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judgecomment',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='accounts.judge'),
        ),
        migrations.AlterField(
            model_name='judgingcriteria',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scores.maincategory'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.judgingcriteria')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='accounts.judge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='register.participant')),
            ],
            options={
                'indexes': [models.Index(fields=['judge', 'participant'], name='scores_poin_judge_i_a96c1b_idx'), models.Index(fields=['criteria'], name='scores_poin_criteri_a83008_idx')],
                'unique_together': {('judge', 'participant', 'criteria')},
            },
        ),
    ]
