# Generated by Django 5.2.4 on 2025-10-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_alter_user_role_authorprofile'),
        ('register', '0017_remove_legacy_models'),
        ('scores', '0002_alter_judgingcriteria_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='score',
            name='contestant',
        ),
        migrations.RemoveField(
            model_name='score',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='score',
            name='judge',
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='point',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='register.registration'),
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('judge', 'participant', 'criteria', 'registration')},
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['registration'], name='scores_poin_registr_94c047_idx'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
