# Generated by Django 4.1 on 2023-12-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_judge_is_judge'),
        ('scores', '0002_alter_judgingcriteria_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judges.judge'),
            preserve_default=False,
        ),
    ]
