# Generated by Django 5.2.4 on 2025-10-15 18:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_alter_user_role_authorprofile'),
        ('register', '0018_remove_legacy_models'),
        ('scores', '0003_remove_legacy_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Design Quality')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this category evaluates')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI (optional)', max_length=50)),
            ],
            options={
                'verbose_name': 'Rubric Category',
                'verbose_name_plural': 'Rubric Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Rubric name (e.g., 'Toy Festival 2025 Rubric')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of scoring approach')),
                ('total_possible_points', models.DecimalField(decimal_places=2, default=100.0, help_text='Total points available across all criteria', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one rubric can be active per program')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this rubric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(help_text='Program this rubric is for', on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='register.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Criterion name (e.g., 'Visual Appeal')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What judges should evaluate')),
                ('guidelines', models.TextField(blank=True, help_text="Scoring guidelines (e.g., '8-10: Excellent, 5-7: Good')")),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum score for this criterion', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=3, default=0.1, help_text='Weight in final score (0.1 = 10%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('category', models.ForeignKey(help_text='Category this criterion belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='rubric_criteria', to='scores.rubriccategory')),
                ('rubric', models.ForeignKey(help_text='Parent rubric', on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scores.rubric')),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JudgingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('raw_score', models.DecimalField(decimal_places=2, help_text='Actual score entered by judge', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible (from criteria at submission time)', max_digits=6)),
                ('score_percentage', models.DecimalField(decimal_places=2, help_text='Normalized to percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weighted_score', models.DecimalField(decimal_places=2, help_text='Score * criteria weight', max_digits=6)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('revision_number', models.PositiveIntegerField(default=1, help_text='Version number (1 = original)')),
                ('revision_reason', models.TextField(blank=True, help_text='Why was this score revised')),
                ('notes', models.TextField(blank=True, help_text="Judge's notes about this score")),
                ('judge', models.ForeignKey(help_text='Judge who gave this score', on_delete=django.db.models.deletion.PROTECT, related_name='judging_scores', to='accounts.judge')),
                ('previous_score', models.ForeignKey(blank=True, help_text='Previous version if revised', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='scores.judgingscore')),
                ('program', models.ForeignKey(help_text='Program being judged', on_delete=django.db.models.deletion.CASCADE, related_name='judging_scores', to='register.program')),
                ('registration', models.ForeignKey(help_text='Participant registration', on_delete=django.db.models.deletion.CASCADE, related_name='judging_scores', to='register.registration')),
                ('criteria', models.ForeignKey(help_text='Criterion being scored', on_delete=django.db.models.deletion.PROTECT, related_name='judging_scores', to='scores.rubriccriteria')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scoring_start', models.DateTimeField(help_text='When judges can start scoring')),
                ('scoring_end', models.DateTimeField(help_text='When scoring closes')),
                ('min_judges_required', models.PositiveIntegerField(default=2, help_text='Minimum judges that must score each participant', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_judges_per_participant', models.PositiveIntegerField(default=3, help_text='Maximum judges allowed per participant', validators=[django.core.validators.MinValueValidator(1)])),
                ('calculation_method', models.CharField(choices=[('AVERAGE_ALL', 'Average All Judges'), ('TOP_N', 'Top N Judges (highest scores)'), ('MEDIAN', 'Median Score'), ('WEIGHTED', 'Weighted Average by Criteria')], default='AVERAGE_ALL', help_text='How to calculate final scores', max_length=20)),
                ('top_n_count', models.PositiveIntegerField(blank=True, help_text='Number of top judges (if method is TOP_N)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_revisions', models.BooleanField(default=True, help_text='Can judges edit scores after submission')),
                ('revision_deadline', models.DateTimeField(blank=True, help_text='Last time judges can revise (blank = same as scoring_end)', null=True)),
                ('max_revisions_per_score', models.PositiveIntegerField(default=3, help_text='Maximum times a score can be revised (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('show_scores_to_participants', models.BooleanField(default=False, help_text='Can participants see their scores')),
                ('scores_visible_after', models.DateTimeField(blank=True, help_text='When scores become visible to participants', null=True)),
                ('program', models.OneToOneField(help_text='Program this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='register.program')),
            ],
            options={
                'verbose_name': 'Scoring Configuration',
            },
        ),
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('relationship_type', models.CharField(choices=[('FAMILY', 'Family Member'), ('TEACHER', 'Teacher/Instructor'), ('EMPLOYER', 'Employer/Employee'), ('SPONSOR', 'Sponsor/Sponsee'), ('FRIEND', 'Close Friend'), ('OTHER', 'Other Relationship')], max_length=20)),
                ('description', models.TextField(help_text='Details about the relationship')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Can Judge)'), ('REJECTED', 'Rejected (Cannot Judge)')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_flagged', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='accounts.judge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_conflicts', to='register.participant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='scores_conf_status_769dfb_idx'), models.Index(fields=['judge', 'status'], name='scores_conf_judge_i_acf0f7_idx')],
                'unique_together': {('judge', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category_value', models.CharField(blank=True, help_text='Category value from program.category_options (blank = all categories)', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Max participants to assign (blank = unlimited)', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this assignment')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(help_text='Assigned judge', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.judge')),
                ('program', models.ForeignKey(help_text='Program to judge', on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='register.program')),
            ],
            options={
                'indexes': [models.Index(fields=['program', 'category_value', 'status'], name='scores_judg_program_5d0733_idx'), models.Index(fields=['judge', 'status'], name='scores_judg_judge_i_c00e44_idx')],
                'unique_together': {('program', 'judge', 'category_value')},
            },
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('program', 'is_active'), name='one_active_rubric_per_program'),
        ),
        migrations.AddIndex(
            model_name='rubriccriteria',
            index=models.Index(fields=['rubric', 'category'], name='scores_rubr_rubric__5213f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubriccriteria',
            unique_together={('rubric', 'name')},
        ),
        migrations.AddIndex(
            model_name='judgingscore',
            index=models.Index(fields=['program', 'registration'], name='scores_judg_program_681881_idx'),
        ),
        migrations.AddIndex(
            model_name='judgingscore',
            index=models.Index(fields=['judge', 'submitted_at'], name='scores_judg_judge_i_9e6515_idx'),
        ),
        migrations.AddIndex(
            model_name='judgingscore',
            index=models.Index(fields=['registration', 'criteria'], name='scores_judg_registr_77859c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='judgingscore',
            unique_together={('program', 'registration', 'judge', 'criteria')},
        ),
    ]
