# Generated by Django 4.1 on 2023-12-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
