# Generated by Django 4.1 on 2023-12-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_contestant_age_category_alter_contestant_email'),
        ('judges', '0002_judge_is_judge'),
        ('scores', '0004_alter_score_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.contestant')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.judge')),
            ],
        ),
    ]
