# Generated by Django 5.2.4 on 2025-12-12 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_remove_legacy_models'),
        ('scores', '0004_add_phase2_judging_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['program', 'category_value', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='rubric',
            name='one_active_rubric_per_program',
        ),
        migrations.AddField(
            model_name='rubric',
            name='category_value',
            field=models.CharField(blank=True, help_text="If set, this rubric applies only to registrations with this category value (e.g., '3-7 years'). If NULL, applies as default/general rubric.", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one rubric can be active per program+category combination'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(help_text="Rubric name (e.g., 'Toy Festival 2025 - Ages 3-7')", max_length=200),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['program', 'category_value', 'is_active'], name='scores_rubr_program_a7595c_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('program', 'category_value'), name='one_active_rubric_per_program_category'),
        ),
    ]
