# Generated by Django 4.1 on 2023-12-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='is_judge',
            field=models.BooleanField(default=True),
        ),
    ]
