# Generated by Django 4.1 on 2023-11-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.parent'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(),
        ),
    ]
