# Generated by Django 4.1 on 2023-11-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_child_parent_alter_child_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
