# Generated by Django 5.1 on 2025-04-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_programtype_program_year_alter_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
