# Generated by Django 4.1 on 2023-11-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_second_name_child_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='identifier',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.parent'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('mm', 'MOBILE MONEY'), ('cash', 'CASH')], max_length=15),
        ),
    ]
