# Generated by Django 5.1 on 2025-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_participant_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='form_key',
            field=models.CharField(default=1, help_text="Front‑end key for the React form component (e.g. 'tf', 'mp')", max_length=50),
            preserve_default=False,
        ),
    ]
