# Generated by Django 5.1 on 2025-04-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_programtype_form_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether program participation is still active'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
