# Generated by Django 5.1 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_program_active_alter_participant_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Portion of the registration fee paid in this approval.', max_digits=8, null=True),
        ),
    ]
