# Generated by Django 5.2.4 on 2025-09-22 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_approval_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('url', 'URL'), ('phone', 'Phone')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='Used for dropdown/radio/checkbox', null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('allowed_file_types', models.JSONField(blank=True, null=True)),
                ('max_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('conditional_logic', models.JSONField(blank=True, help_text='Rules for showing this field', null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='form_uploads/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.formfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='register.formresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used when auto-selecting forms')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='register.program')),
            ],
            options={
                'ordering': ['program', 'age_min'],
                'unique_together': {('program', 'title')},
            },
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='register.programform'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='register.programform'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field_name')},
        ),
    ]
