# Generated by Django 5.2.4 on 2025-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_formfield_formresponse_formresponseentry_programform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, help_text="Program duration (e.g., '8 weeks')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether this is a featured program'),
        ),
        migrations.AddField(
            model_name='program',
            name='instructor',
            field=models.CharField(blank=True, help_text='Instructor name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list, help_text='List of learning outcomes'),
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Skill level required', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed program description', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='List of curriculum modules'),
        ),
        migrations.AddField(
            model_name='program',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisites and requirements'),
        ),
        migrations.AddField(
            model_name='program',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='video_url',
            field=models.URLField(blank=True, help_text='Preview video URL', null=True),
        ),
    ]
