# Generated by Django 5.2.4 on 2025-09-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_add_program_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
    ]
