# Generated by Django 4.2.16 on 2025-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_remove_duration_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category_label',
            field=models.CharField(blank=True, help_text="Label shown on forms for participant categorisation (e.g. 'Age Group').", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='category_options',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed category values (e.g. ['6-9 years', '10-13 years']). Leave empty for free text."),
        ),
        migrations.AddField(
            model_name='registration',
            name='category_value',
            field=models.CharField(blank=True, help_text='Participant-chosen category for this program (matches Program.category_options if provided).', max_length=120, null=True),
        ),
    ]
