# Generated by Django 5.2.4 on 2025-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_program_category_label_program_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programform',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Active form for program registration'),
        ),
    ]
