# Generated by Django 5.2.4 on 2025-09-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_add_timestamps_to_program_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='register.registration'),
        ),
    ]
