# Generated by Django 5.2.4 on 2025-10-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_add_partially_paid_status'),
        ('register', '0015_programform_step_metadata_formfield_step_key_and_more'),
    ]

    operations = [
    ]
