# Generated by Django 5.2.4 on 2025-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_merge_20251015_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='participant',
        ),
        migrations.AddField(
            model_name='program',
            name='is_judgable',
            field=models.BooleanField(default=False, help_text='Whether this program requires judging/scoring'),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
