# Generated by Django 5.2.4 on 2025-10-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_remove_legacy_models'),
        ('scores', '0003_remove_legacy_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contestant',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
