# Generated by Django 5.2.4 on 2025-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_remove_legacy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='programs/logos/'),
        ),
    ]
